In [48]:
import pandas as pd
import os
from sklearn.tree import DecisionTreeClassifier
import numpy as np


'''这种x:pd.Series的写法是为了方便开发人员理解，实际并不能对类型固定
包括->list也只是参考作用，不起实际效果
'''
def optimal_binning_boundary(x:pd.Series,y:pd.Series,nan: float=-999.)->list:
    
    boundary = []
    
    x=x.fillna(nan).values #-999.补空值
    
    y=y.values #变成array
    
    clf=DecisionTreeClassifier(criterion='entropy',
                               max_leaf_nodes=6,
                               min_samples_leaf=0.05)
    
    clf.fit(x.reshape(-1,1),y)
    
    n_nodes = clf.tree_.node_count
    
    children_left=clf.tree_.children_left
    
    children_right=clf.tree_.children_right
    
    threshold=clf.tree_.threshold
    
    for i in range(n_nodes):
        if children_left[i] != children_right[i]:
            boundary.append(threshold[i])
            
    boundary.sort()
    
    min_x=x.min()
    max_x=x.max()+0.1
    boundary = [min_x]+boundary+[max_x]
    
    return boundary


def feature_woe_iv(x:pd.Series,y:pd.Series,nan:float=-999.) -> pd.DataFrame:
    
    x = x.fillna(nan)
    
    boundary=optimal_binning_boundary(x,y,nan)
    
    df=pd.concat([x,y],axis=1)
    
    df.columns = ['x','y']
    
    df['bins'] = pd.cut(x=x, bins=boundary, right=False)#按区间分bin
    
    grouped = df.groupby('bins')['y'] #此处只留下了target Y在分bin的group里
    
    result_df=grouped.agg([('good', lambda y: (y==1).sum()), 
                           ('bad', lambda y: (y==0).sum()),
                           ('total','count')
                           ]) #agg为groupby后在一个轴上进行多项不同的聚合函数
    '''lambda函数里，y==0判断的是grouped列里每个值是否是0，返回True False.
    最后聚合sum的是True的个数'''
    
    result_df['good_pct'] = result_df['good'] / result_df['good'].sum()
    result_df['bad_pct'] = result_df['bad'] / result_df['bad'].sum()
    result_df['total_pct'] = result_df['total'] / result_df['total'].sum()
    
    result_df['bad_rate'] = result_df['bad']/result_df['total']
    
    result_df['woe'] = np.log(result_df['good_pct'] / result_df['bad_pct'])
    
    result_df['iv'] = (result_df['good_pct'] - result_df['bad_pct'])*result_df['woe']
    result_df['feature_name'] = x.name
    result_df.reset_index(inplace=True)

    
    print(f"该变量IV={result_df['iv'].sum()}")
    
    return result_df

In [49]:
root_path = os.path.dirname(os.getcwd())
data_path = os.path.join(root_path,  'data')

In [50]:
data = pd.read_csv(data_path+'/train.csv')

In [51]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [52]:
data.loc[data['tenure']==0, 'tenure'] = 1
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')
data['TotalCharges'] = np.where(data['TotalCharges'].isnull(), data['MonthlyCharges'], data['TotalCharges'])

In [53]:
x = data[['tenure', 'TotalCharges', 'MonthlyCharges']]
y = data['Churn'].map({"Yes":1, 'No':0})

In [54]:
type(x['TotalCharges'][0])

numpy.float64

In [55]:
df = pd.DataFrame()
for i in x.columns:
    temp = feature_woe_iv(x[i], y)
    print(temp)
    df = df.append(temp)

该变量IV=0.8447246198309861
           bins  good  bad  total  good_pct   bad_pct  total_pct  bad_rate  \
0    [1.0, 5.5)   624  551   1175  0.390244  0.123987   0.194440  0.468936
1   [5.5, 22.5)   487  958   1445  0.304565  0.215572   0.239120  0.662976
2  [22.5, 43.5)   271  978   1249  0.169481  0.220072   0.206685  0.783026
3  [43.5, 59.5)   133  771    904  0.083177  0.173492   0.149595  0.852876
4  [59.5, 70.5)    75  729    804  0.046904  0.164041   0.133047  0.906716
5  [70.5, 72.1)     9  457    466  0.005629  0.102835   0.077114  0.980687

        woe        iv feature_name
0  1.146592  0.305288       tenure
1  0.345593  0.030756       tenure
2 -0.261214  0.013215       tenure
3 -0.735163  0.066396       tenure
4 -1.252009  0.146657       tenure
5 -2.905282  0.282413       tenure
该变量IV=0.36727212952359994
                 bins  good   bad  total  good_pct   bad_pct  total_pct  \
0      [18.8, 58.575)   154   228    382  0.096310  0.051305   0.063214
1    [58.575, 96.625)   205   108    313  0.128205  0.024302   0.051795
2     [96.625, 347.9)   259   467    726  0.161976  0.105086   0.120139
3     [347.9, 1182.8)   364   961   1325  0.227642  0.216247   0.219262
4  [1182.8, 3763.525)   409  1386   1795  0.255785  0.311881   0.297038
5  [3763.525, 8684.9)   208  1294   1502  0.130081  0.291179   0.248552

   bad_rate       woe        iv  feature_name
0  0.596859  0.629783  0.028343  TotalCharges
1  0.345048  1.663055  0.172796  TotalCharges
2  0.643251  0.432675  0.024615  TotalCharges
3  0.725283  0.051356  0.000585  TotalCharges
4  0.772145 -0.198286  0.011123  TotalCharges
5  0.861518 -0.805779  0.129809  TotalCharges
该变量IV=0.5053995265081178
                bins  good   bad  total  good_pct   bad_pct  total_pct  \
0    [18.25, 27.675)   129  1267   1396  0.080675  0.285104   0.231011
1   [27.675, 50.925)   211   461    672  0.131957  0.103735   0.111203
2   [50.925, 57.575)    63   253    316  0.039400  0.056931   0.052292
3   [57.575, 69.225)    57   422    479  0.035647  0.094959   0.079265
4  [69.225, 106.975)  1092  1771   2863  0.682927  0.398515   0.473771
5  [106.975, 118.85)    47   270    317  0.029393  0.060756   0.052457

   bad_rate       woe        iv    feature_name
0  0.907593 -1.262418  0.258074  MonthlyCharges
1  0.686012  0.240637  0.006791  MonthlyCharges
2  0.800633 -0.368078  0.006453  MonthlyCharges
3  0.881002 -0.979778  0.058113  MonthlyCharges
4  0.618582  0.538643  0.153197  MonthlyCharges
5  0.851735 -0.726098  0.022772  MonthlyCharges

In [57]:
df.to_excel('woe_iv.xlsx', index=False)

In [47]:
temp

,good,bad,total,good_pct,bad_pct,total_pct,bad_rate,woe,iv,feature_name
bins,,,,,,,,,,
"[18.8, 58.575)",154,228,382,0.096310,0.051305,0.063214,0.596859,0.629783,0.028343,TotalCharges
"[58.575, 96.625)",205,108,313,0.128205,0.024302,0.051795,0.345048,1.663055,0.172796,TotalCharges
"[96.625, 347.9)",259,467,726,0.161976,0.105086,0.120139,0.643251,0.432675,0.024615,TotalCharges
"[347.9, 1182.8)",364,961,1325,0.227642,0.216247,0.219262,0.725283,0.051356,0.000585,TotalCharges
"[1182.8, 3763.525)",409,1386,1795,0.255785,0.311881,0.297038,0.772145,-0.198286,0.011123,TotalCharges
"[3763.525, 8684.9)",208,1294,1502,0.130081,0.291179,0.248552,0.861518,-0.805779,0.129809,TotalCharges